<LoginScreen@MDScreen>:
    name: "login"

    MDBoxLayout:
        orientation: "vertical"
        spacing: "20dp"
        padding: "40dp"
        pos_hint: {"center_x": 0.5, "center_y": 0.5}

        MDLabel:
            text: "💰 App de Finanças"
            halign: "center"
            font_style: "H4"
            size_hint_y: None
            height: "100dp"

        MDTextField:
            id: usuario
            hint_text: "Usuário"
            icon_right: "account"
            mode: "rectangle"

        MDTextField:
            id: senha
            hint_text: "Senha"
            password: True
            icon_right: "key"
            mode: "rectangle"

        MDRaisedButton:
            text: "ENTRAR"
            pos_hint: {"center_x": 0.5}
            size_hint_x: 0.8
            on_release: root.login()

        MDFlatButton:
            text: "Não tem conta? Crie aqui"
            pos_hint: {"center_x": 0.5}
            on_release: app.root.current = "cadastro"  # <-- Agora leva para a tela nova

        MDTextButton:
            text: "Esqueci minha senha"
            pos_hint: {"center_x": 0.5}
            custom_color: "blue"
            on_release: app.root.current = "recuperar"
