<MovimentacaoScreen@MDScreen>:
    tipo: "receita"
    MDBoxLayout:
        orientation: "vertical"
        spacing: "20dp"
        padding: "20dp"

        MDLabel:
            text: "Registrar Movimentação"
            halign: "center"
            font_style: "H5"
            size_hint_y: None
            height: "-15dp"

        MDDropDownItem:
            id: categoria
            text: "Selecione uma categoria"
            on_release: app.abrir_menu_categorias(self)
            pos_hint: {"center_x": 0.5}
            size_hint_y: None
            height: "-17dp"


        MDTextField:
            id: valor
            hint_text: "Valor (ex: 150.00)"
            input_filter: "float"
            size_hint_y: None
            height: "-17dp"

        MDTextField:
            id: descricao
            hint_text: "Descrição"
            size_hint_y: None
            height: "-17dp"

        MDRaisedButton:
            text: "Salvar"
            pos_hint: {"center_x": 0.5}
            on_release:
                app.root.get_screen(root.name).registrar()

        ScrollView:
            size_hint_y: None
            height: "250dp"

            MDBoxLayout:
                id: grafico_box
                orientation: "vertical"
                size_hint_y: None
                height: self.minimum_height
                spacing: "10dp"

                MDLabel:
                    id: resultado
                    text: ""
                    halign: "left"
                    valign: "top"
                    text_size: self.width, None
                    size_hint_y: None
                    height: self.texture_size[1] + 20

        MDFlatButton:
            text: "Voltar"
            pos_hint: {"center_x": 0.5}
            on_release:
                app.root.current = "menu"
