<RecuperarScreen>:
    name: "recuperar"

    MDBoxLayout:
        orientation: "vertical"
        padding: "30dp"
        spacing: "20dp"

        MDLabel:
            text: "🔐 Recuperar Senha"
            halign: "center"
            font_style: "H5"
            size_hint_y: None
            height: "50dp"

        MDTextField:
            id: user_input
            hint_text: "Digite seu Usuário"
            mode: "rectangle"

        MDRaisedButton:
            text: "Buscar Pergunta"
            pos_hint: {"center_x": 0.5}
            on_release: root.buscar_pergunta()

        MDLabel:
            id: label_pergunta
            text: "Pergunta aparecerá aqui..."
            halign: "center"
            theme_text_color: "Secondary"
            size_hint_y: None
            height: "40dp"

        MDTextField:
            id: resposta_input
            hint_text: "Sua Resposta"
            disabled: True
            mode: "rectangle"

        MDTextField:
            id: nova_senha_input
            hint_text: "Nova Senha"
            password: True
            disabled: True
            mode: "rectangle"

        MDRaisedButton:
            id: btn_resetar
            text: "Redefinir Senha"
            disabled: True
            pos_hint: {"center_x": 0.5}
            on_release: root.confirmar_reset()

        MDFlatButton:
            text: "Voltar ao Login"
            pos_hint: {"center_x": 0.5}
            on_release: app.root.current = "login"