<CadastroScreen>:
    name: "cadastro"

    MDBoxLayout:
        orientation: "vertical"
        padding: "30dp"
        spacing: "15dp"
        pos_hint: {"center_x": 0.5, "center_y": 0.5}

        # ScrollView ajuda se a tela for pequena
        ScrollView:
            MDBoxLayout:
                orientation: "vertical"
                adaptive_height: True
                spacing: "15dp"

                MDLabel:
                    text: "📝 Criar Nova Conta"
                    halign: "center"
                    font_style: "H5"
                    size_hint_y: None
                    height: "50dp"

                MDTextField:
                    id: usuario
                    hint_text: "Escolha um Usuário"
                    icon_right: "account-plus"
                    mode: "rectangle"

                MDTextField:
                    id: nome
                    hint_text: "Seu Nome Completo"
                    icon_right: "card-account-details"
                    mode: "rectangle"

                MDTextField:
                    id: senha
                    hint_text: "Escolha uma Senha"
                    password: True
                    icon_right: "key-variant"
                    mode: "rectangle"

                MDTextField:
                    id: pergunta
                    hint_text: "Pergunta de Segurança"
                    helper_text: "Ex: Nome da mãe? Primeira escola?"
                    helper_text_mode: "on_focus"
                    mode: "rectangle"

                MDTextField:
                    id: resposta
                    hint_text: "Resposta de Segurança"
                    password: True
                    mode: "rectangle"

                MDRaisedButton:
                    text: "Confirmar Cadastro"
                    pos_hint: {"center_x": 0.5}
                    on_release: root.cadastrar()

                MDFlatButton:
                    text: "Já tenho conta (Voltar)"
                    pos_hint: {"center_x": 0.5}
                    on_release: app.root.current = "login"