<RelatorioScreen@MDScreen>:
    name: "relatorio"

    MDBoxLayout:
        orientation: "vertical"
        padding: "20dp"
        spacing: "10dp"

        MDLabel:
            text: "📊 Relatório Financeiro"
            halign: "center"
            font_style: "H5"
            size_hint_y: None
            height: "50dp"

        ScrollView:
            MDBoxLayout:
                id: content_box
                orientation: "vertical"
                size_hint_y: None
                height: self.minimum_height
                spacing: "10dp"

                MDLabel:
                    id: resultado
                    text: "Gerando relatório..."
                    halign: "left"
                    valign: "top"
                    text_size: self.width, None
                    size_hint_y: None
                    height: self.texture_size[1] + 20

                BoxLayout:
                    id: grafico_box
                    size_hint_y: None
                    height: "220dp"
                    padding: "10dp"
                    orientation: "vertical"

        MDFlatButton:
            text: "Voltar"
            pos_hint: {"center_x": 0.5}
            on_release: app.root.current = "menu"




<ReceitasScreen>:
    name: "receitas"
    MDBoxLayout:
        orientation: "vertical"
        spacing: "10dp"
        padding: "10dp"

        MDLabel:
            text: "Relatório de Receitas"
            halign: "center"
            theme_text_color: "Primary"
            font_style: "H5"

        ScrollView:
            MDLabel:
                id: receitas_text
                text: "Nenhuma receita encontrada."
                halign: "center"
                size_hint_y: None
                height: self.texture_size[1]

        BoxLayout:
            id: grafico_box
            size_hint_y: 0.5
            orientation: "vertical"
            padding: "10dp"

        MDRaisedButton:
            text: "Voltar"
            size_hint_y: None
            height: "48dp"
            on_release: app.root.current = "menu"


<DespesasScreen>:
    name: "despesas"
    MDBoxLayout:
        orientation: "vertical"
        spacing: "10dp"
        padding: "10dp"

        MDLabel:
            text: "Relatório de Despesas"
            halign: "center"
            theme_text_color: "Primary"
            font_style: "H5"

        ScrollView:
            MDLabel:
                id: despesas_text
                text: "Nenhuma despesa encontrada."
                halign: "center"
                size_hint_y: None
                height: self.texture_size[1]

        BoxLayout:
            id: grafico_box
            size_hint_y: 0.5
            orientation: "vertical"
            padding: "10dp"

        MDRaisedButton:
            text: "Voltar"
            size_hint_y: None
            height: "48dp"
            on_release: app.root.current = "menu"
